feat(temporarily-restores-xva): Add function to test a XVA file restoration (#3)
* feat(export-metadata): export SR-ID with VM

* chore(namings): Rename LOCAL_XVA_DIR LOCAL_TMP_DIR

* feat(temporarily-restores-xva): Add function

This function imports the VM from the XVA file and deletes it right
away.
It's the best and most trustable way to ensure a XVA file can be
restored.

Also, some metadata were necessary to export.

Some vars were renamed and some comments were changed to better fit
reality.

* feat(WORKING_DIR): Refacto creation/rm directory

Working directory was kind of a mess.
This commit to give coherence in the way files are created and removed.
E.g, if vm metadata export fails, no need to remove the whole dir.

The whole WORKING_DIR is removed only when everything has been tested
and pushed to S3

* feat(xo_cli_wrap): Move to xo-cli when necessary

wrapper is not necessary when functions are captured in a subshell,
it's better and avoid unecessary errors to switch to the raw binary
instead of using a non-working wrapper in such situations

* fix(auth): Force auth_renew in some cases

some functions need to redirect stdout (E.g, into a .json) when calling
xo-cli, and that messes up with xo-cli asking for credentials
(ask-for-pass isn't displayed, script gets stucked)

Adding `renew_xo_cli_auth` at the begining of the Main phase so we renew
auth in any case (as of today, only copy_s3 doesn't interract with XO)

Changed from `xo_cli_wrap` to `xo-cli` anytime output is redirected to
avoid any expired credentials error.
Also, added a `renew_xo_cli_auth` everytime `xo_cli_wrap` was changed to
`xo-cli`

* fixup! fix(auth): Force auth_renew in some cases

* feat(comments): Enhance comments and logs

Logs were not that much explicit some times, nor were comments.

* feat(archive): Add temporarily_restores_xva

Now, when archiving a VM, we ensure it's XVA is restorable by actually
restoring it in a temporary VM that we delete right away.

That ensures that archived files are healthy

* chore(Readme): Update readme from latest script

* feat(Readme): Add tree to push command

it's more clear with a visual like "tree" to see the output that
will exist on the bucket

* fixup! feat(Readme): Add tree to push command

* Apply suggestions from code review

Co-authored-by: Julien Menan <50320627+jmenan@users.noreply.github.com>

* feat(CONTRIBUTING.md): Add file

* feat(xo-archiver): Add execute mode to script

Co-authored-by: Julien Menan <50320627+jmenan@users.noreply.github.com>

diff --git a/xo-archiver b/xo-archiver
--- a/xo-archiver
+++ b/xo-archiver
@@ -25,23 +25,37 @@ SYNOPSIS: $0 <COMMAND> <SELECTOR> [OPTIONS]
 
 COMMANDS:
   export
-        Creates a manual export of a VM in a compressed and restorable format
+        Creates a manual export of a VM in a compressed and restorable format (XVA)
+        Also exports some metadata needed to restore the VM to the same location
         To be used with --vm-id or --vm-name
 
   push
-        Pushes the given export to S3.
+        Pushes exported files (XVA+metadata) to S3.
         To be used with --vm-id or --vm-name
         S3 bucket name should be define as an envvar, see below CONFIG FILE section.
+        Files will be pushed to S3 into "s3://bucket_name/\$VM-NAME/", like:
+            foo-bar-01
+            ├── 622870c0-0d21-286b-df2d-05ff2bab6a45.xva
+            ├── SR-ID.txt
+            └── VM.json
 
   delete
         Deletes the Virtual Machine and its associated disks in XOA
         To be used with --vm-id or --vm-name
 
   archive
-        Calls the above commands, in this order: export, push and delete
+        Calls those commands, in this order: export, temporarily-restores-xva, push and delete
+        To be used with --vm-id or --vm-name
 
   import
         Imports the specified XVA file (compressed zstd) into the specified SR.
+        To be used with --sr-id and --xva-file
+
+  temporarily-restores-xva
+        Restores the given XVA file into the specified Storage Repository,
+        and deletes this newly created VM right away.
+        This command ensures that the file is restorable by actually restoring it,
+        and deleting the VM thus created. VM will stay in Halted state all along.
         To be used with --sr-id and --xva-file
 
 
@@ -98,12 +112,12 @@ CONFIG FILE:
         It uses the "date" binary format
         Defaults to '24hour'
 
-  LOCAL_XVA_DIR
-        Local directory in which XVA will be temporary stored
-        Defaults to '/tmp/xva_dir'
+  LOCAL_TMP_DIR
+        Local directory in which files will be temporary stored
+        Defaults to '/tmp/xo-archiver'
 
-  AWS_BUCKET_XVA_ARCHIVES
-        AWS's S3 bucket name where XVA files are archived
+  AWS_BUCKET_XO_ARCHIVES
+        AWS's S3 bucket name where files are archived
         E.g: my-xen-archives
         AWS cli also uses other envvars like AWS_ACCESS_KEY_ID, etc.
         All those envvars can be defined inside config file,
@@ -198,9 +212,9 @@ then
     # https://github.com/vatesfr/xen-orchestra/blob/master/packages/xo-server/config.toml#L45
 fi
 
-if [[ -z "$LOCAL_XVA_DIR" ]]
+if [[ -z "$LOCAL_TMP_DIR" ]]
 then 
-    LOCAL_XVA_DIR=/tmp/xva_dir
+    LOCAL_TMP_DIR=/tmp/xo-archiver
 fi
 
 
@@ -244,7 +258,7 @@ function renew_xo_cli_auth {
 # Register the cli to the specified XO host
 # needs envvar: $XO_HOST $XO_USER
 function xo_register {
-    log "registering to $XO_HOST with user $XO_USER"
+    log "Registering to $XO_HOST with user $XO_USER"
     
     # following register will ask for password
     \xo-cli --register --expiresIn $XO_CLI_EXPIRE $XO_HOST $XO_USER || die "can't register"
@@ -258,58 +272,127 @@ function xo_register {
 # Usage: xo_cli_wrap vm.export --foo --bar
 # will renew token to access xo-cli
 # and load xo-cli with all parameters in a transparent manner
+# /!\ You shouldn't use this wrapper if you redirect stdout, that messes up with
+# xo-cli asking for credentials (ask-for-pass isn't displayed, script gets stucked) /!\
 function xo_cli_wrap {
     renew_xo_cli_auth
     \xo-cli "$@"
 }
 
 
-# Usage: clean_local_xva_dir
-# Removes all tmp files and dir
-function clean_local_xva_dir {
-    log "Cleaning up $LOCAL_XVA_DIR/"
-    rm -Rf $LOCAL_XVA_DIR/*
+# Usage: create_working_dir
+# Creates the temporary directory
+function create_working_dir {
+    if [[ ! -d "$WORKING_DIR" ]]
+    then
+        log "Creating $WORKING_DIR"
+        mkdir -p $WORKING_DIR
+    fi
 }
 
 
-# Usage: export <VM-ID>
+# Usage: export_vm <VM-ID>
 # Will exports the specified VM in compressed zstd, in a .xva file
 function export_vm {
     if [[ -z $1 ]]
     then
-        die "export needs parameter: VM-ID. E.g: 622870c0-0d21-286b-df2d-05ff2bab6a45"
+        die "export_vm needs parameter: VM-ID. E.g: 622870c0-0d21-286b-df2d-05ff2bab6a45"
     fi
 
-    clean_local_xva_dir
+    create_working_dir
 
-    local _vm_export_path="$LOCAL_XVA_DIR/${1}/${1}.xva"
+    local _vm_export_path="$WORKING_DIR/${1}.xva"
     log "Exporting VM into \"$_vm_export_path\""
-    mkdir -p $(dirname $_vm_export_path)
+    rm $_vm_export_path 2>/dev/null
 
     if xo_cli_wrap vm.export vm=$1 @=$_vm_export_path compress=zstd
     then
         log "Export completed at \"$_vm_export_path\""
+        # this exported envvar is used in Main to call temporarily_restores_xva function
+        export EXPORTED_VM_XVA_FILE=$_vm_export_path
     else
-        clean_local_xva_dir
-        die "export failed"
+        rm -f $_vm_export_path
+        die "Export failed for VM \"${1}\""
     fi
 }
 
 
-# Usage: import <SR-ID> <XVA-local-path>
+# Usage: export_metadata <VM-ID>
+# Will exports metadata of the specified VM into the backup directory
+function export_metadata {
+    if [[ -z $1 ]]
+    then
+        die "export_metadata needs parameter: VM-ID. E.g: 622870c0-0d21-286b-df2d-05ff2bab6a45"
+    fi
+
+    create_working_dir
+    log "Exporting metadata into \"$WORKING_DIR/\""
+
+    # Exporting VM metadata
+    # using xo-cli and not wrapper here, because we redirect stdout (incompatible with ask-for-pass)
+    # still, we try to renew auth to avoid expired credential error
+    renew_xo_cli_auth
+    if xo-cli --list-objects type=VM id=$1 > $WORKING_DIR/VM.json
+    then
+        log "VM metadata successfully exported to $WORKING_DIR/VM.json"
+    else
+        rm -f $WORKING_DIR/VM.json
+        die "Unable to export VM metadata for VM \"$1\""
+    fi
+
+    # Exporting Storage Repository ID for futur import
+    ## Export VDI-IDs from VBD to get SR
+    for VDI in $(xo-cli --list-objects type=VBD VM=${1} | jq -r '.[].VDI|values')
+    do
+        # using xo-cli and not wrapper here, because we redirect stdout (incompatible with ask-for-pass)
+        xo-cli --list-objects type=VDI id=$VDI | \
+            jq -r '.[]."$SR"|values' >> $WORKING_DIR/VDI-${VDI}-SR-ID.txt
+    done
+
+    # get first SR from VDIs and check if result looks good
+    grep --no-filename -E "[a-Z0-9]" $WORKING_DIR/VDI-*-SR-ID.txt | head -1 > $WORKING_DIR/SR-ID.txt
+    # this exported envvar is used in Main to call temporarily_restores_xva function
+    export EXPORTED_VM_SR_ID="$(cat $WORKING_DIR/SR-ID.txt)"
+
+    if echo $EXPORTED_VM_SR_ID | grep -q "[a-Z0-9]"
+    then
+        rm -f $WORKING_DIR/VDI-*-SR-ID.txt
+        log "Storage Repository ID \"$EXPORTED_VM_SR_ID\" exported to $WORKING_DIR/SR-ID.txt"
+    else
+        rm -f $WORKING_DIR/{SR-ID.txt,VDI-*-SR-ID.txt}
+        unset $EXPORTED_VM_SR_ID
+        die "Unable to export Storage Repository ID for VM \"$1\""
+    fi
+}
+
+
+# Usage: import_vm <SR-ID> <XVA-local-path>
 # Will import the specified XVA file (compressed zstd) into the specified SR
 function import_vm {
     if [[ -z $2 ]]
     then
-        die "import needs 2 parameters: <SR-ID> <XVA-local-path>"
+        die "import_vm needs 2 parameters: <SR-ID> <XVA-local-path>"
     fi
 
     log "Importing VM from \"$2\""
 
-    if xo_cli_wrap vm.import sr=$1 @=$2
+    # using xo-cli and not wrapper here, because we redirect stdout (incompatible with ask-for-pass)
+    # still, we try to renew auth to avoid expired credential error
+    renew_xo_cli_auth
+    if xo-cli vm.import sr=$1 @=$2 > $2-imported.json
     then
-        log "Import completed"
+        # This new VM-ID is necessary to run temporarily_restores_xva function
+        # but it also improves the output log
+        export IMPORTED_VM_ID=$(jq --exit-status -r '.result' '$2-imported.json' )
+        if ! echo $IMPORTED_VM_ID | grep -q "[a-Z0-9]"
+        then
+            unset $IMPORTED_VM_ID
+            log "Can't get a valid VM-ID from import. You must check manually in XOA"
+        fi
+        log "Import completed into \"$IMPORTED_VM_ID\""
+        rm -f $2-imported.json
     else
+        rm -f $2-imported.json
         die "Import failed"
     fi
 }
@@ -320,41 +403,70 @@ function import_vm {
 function delete_vm {
     if [[ -z $1 ]]
     then
-        die "delete needs parameter: VM-ID. E.g: 622870c0-0d21-286b-df2d-05ff2bab6a45"
+        die "delete_vm needs parameter: VM-ID. E.g: 622870c0-0d21-286b-df2d-05ff2bab6a45"
     fi
 
-    if xo_cli_wrap vm.delete id=${1} deleteDisks=true >/dev/null
+    log "Deleting VM \"$1\""
+
+    # using xo-cli and not wrapper here, because we redirect stdout (incompatible with ask-for-pass)
+    # still, we try to renew auth to avoid expired credential error
+    renew_xo_cli_auth
+    if xo-cli vm.delete id=${1} deleteDisks=true >/dev/null
     then
-        log "VM has been deleted"
+        log "Successfully deleted VM \"$1\""
     else
-        die "delete failed"
+        die "Delete failed for VM \"$1\""
     fi
 }
 
 
 # Usage: copy_to_s3 <VM-ID>
-# copies the <VM-ID> corresponding XVA into the s3 bucket specified through envvar
+# copies the <VM-ID> corresponding files into the s3 bucket specified through envvar
 function copy_to_s3 {
     # ensure bucket var is set
-    if [[ -z "$AWS_BUCKET_XVA_ARCHIVES" ]]
+    if [[ -z "$AWS_BUCKET_XO_ARCHIVES" ]]
     then 
-        die "Bucket is undefined. look at the --help and search for AWS_BUCKET_XVA_ARCHIVES"
+        die "Bucket is undefined. look at the --help and search for AWS_BUCKET_XO_ARCHIVES"
     fi
 
     # ensure there's something to push (directory exists and not empty)
-    if [[ ! -d $LOCAL_XVA_DIR/${1}/ ]] || ! ls -A $LOCAL_XVA_DIR/${1}/ | grep -q "[a-Z]"
+    if [[ ! -d $WORKING_DIR/ ]] || ! ls -A $WORKING_DIR/ | grep -q "[a-Z0-9]"
     then
-        die "Nothing to push: local directory doesn't exist or empty: \"$LOCAL_XVA_DIR/${1}/\""
+        die "Nothing to push: local directory doesn't exist or empty: \"$WORKING_DIR/\""
     fi
 
     local _vm_name=$(get_vm_name_from_id ${1})
-    local _remote_xva_path="s3://$AWS_BUCKET_XVA_ARCHIVES/$_vm_name"
-    log "Copying export of $_vm_name into \"$_remote_xva_path\""
+    local _remote_xva_path="s3://$AWS_BUCKET_XO_ARCHIVES/$_vm_name"
+    log "Copying export of \"$_vm_name\" into \"$_remote_xva_path\""
 
-    aws s3 cp $LOCAL_XVA_DIR/${1}/ $_remote_xva_path/ --recursive || \
-        die "fail to push to s3"
+    if aws s3 cp $WORKING_DIR/ $_remote_xva_path/ --recursive
+    then
+        log "Successfully copied exports of \"$_vm_name\" on bucket \"$AWS_BUCKET_XO_ARCHIVES\""
+        log "Cleaning up $WORKING_DIR/"
+        rm -Rf $WORKING_DIR/
+    else
+        die "Fail to push to s3"
+    fi
+}
 
-    clean_local_xva_dir
+
+# Usage: temporarily_restores_xva <SR-ID> <XVA-local-path>
+# Will restore the XVA in the specified SR and delete this newly created VM right away
+function temporarily_restores_xva {
+    # no verification of the parameters as they're already done in import_vm function
+    if import_vm "$@"
+    then
+        # var IMPORTED_VM_ID is exported from import_vm function
+        if delete_vm $IMPORTED_VM_ID
+        then
+            log "Successfully restored VM from XVA file \"$2\" and the temporary VM \"$IMPORTED_VM_ID\" has been deleted"
+        else
+            log "VM could be restored from \"$2\", but cannot be removed, you must delete it manually: \"$IMPORTED_VM_ID\""
+            die "If the problem isn't related to the XVA file, you can reload this script with [push] command"
+        fi
+    else
+        die "Import failed, XVA file may be corrupted: \"$2\""
+    fi
 }
 
 
@@ -362,7 +474,7 @@ function copy_to_s3 {
 # Will print the name_label of the given <VM-ID>
 # prints <VM-ID> in case of error
 function get_vm_name_from_id {
-    xo_cli_wrap --list-objects type=VM id=${1} | jq --exit-status -r '.[0].name_label' || \
+    xo-cli --list-objects type=VM id=${1} | jq --exit-status -r '.[0].name_label' || \
         echo "${1}"
 }
 
@@ -371,8 +483,8 @@ function get_vm_name_from_id {
 # Will print the VM-ID of the given <name_label>
 # exits with error message when nothing has been found
 function get_vm_id_from_name {
-    xo_cli_wrap --list-objects type=VM name_label=${1} | jq --exit-status -r '.[0].id' || \
-        die "no VM can be found under name=\"${1}\""
+    xo-cli --list-objects type=VM name_label=${1} | jq --exit-status -r '.[0].id' || \
+        die "No VM can be found under name=\"${1}\""
 }
 
 
@@ -380,13 +492,15 @@ function get_vm_id_from_name {
 ######
 # Main
 
+# calling renew here, because some functions need to redirect stdout (E.g, into a .json)
+# and that messes up with xo-cli asking for credentials (ask-for-pass isn't displayed, script gets stucked)
+renew_xo_cli_auth
+
 # One of the selectors must be provided
 if [[ -z $vm_id ]]
 then
     if [[ ! -z $vm_name ]]
     then
-        # calling renew here, because following subshell traps inputs and outputs
-        renew_xo_cli_auth
         # VM name found but no ID
         vm_id=$(get_vm_id_from_name $vm_name)
         # because it's a subshell, embeded die doesn't make the whole script to die
@@ -400,18 +514,24 @@ then
     fi
 fi
 
+
+WORKING_DIR="$LOCAL_TMP_DIR/$vm_id"
+
 log "Script command=\"$command\""
 
 
 case "$command" in
     export)
         export_vm $vm_id
+        export_metadata $vm_id
         ;;
     push)
         copy_to_s3 $vm_id
         ;;
     archive)
         export_vm $vm_id
+        export_metadata $vm_id
+        temporarily_restores_xva $EXPORTED_VM_SR_ID $EXPORTED_VM_XVA_FILE
         copy_to_s3 $vm_id
         delete_vm $vm_id
         ;;
@@ -421,7 +541,10 @@ case "$command" in
     import)
         import_vm $sr_id $xva_file
         ;;
+    temporarily-restores-xva)
+        temporarily_restores_xva $sr_id $xva_file
+        ;;
     * )
-        die "unknown command \"$command\""
+        die "Unknown command \"$command\""
         ;;
 esac
